spring.application.name=disbursement-saga
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/disbursement_saga_db
spring.datasource.username=root
spring.datasource.password=Sharvarishalgar@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

services.kyc.base-url=http://localhost:8080
services.audit.base-url=http://localhost:8081
services.notification.base-url=http://localhost:8085
services.compliance.base-url=http://localhost:8086