spring.application.name=FinCore Digital Banking Management Platform2
spring.profiles.active=local
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
logging.level.root=INFO
jwt.secret=${JWT_SECRET}
spring.profiles.default=local
