server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fincore-banking-platform
  datasource:
    url: jdbc:mysql://localhost:3306/fincore_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${root:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

fincore:
  npa:
    sma0-days: 30
    sma1-days: 60
    sma2-days: 90
    npa-days: 90
    standard-provision: 0.4
    sma-provision: 5.0
    npa-provision: 15.0
