import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';

import { Router } from '@angular/router';

import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

import {
  PaymentInitiationService,
  UserAccount,
} from './payment-initiation.service';

import { Beneficiary } from './models/beneficiary.model';
import { Payment } from './models/payment.model';
import { FraudCheck } from './models/fraud-check.model';

export type FlowStep = 'FORM' | 'REVIEW' | 'PROCESSING' | 'SUCCESS';

@Component({
  selector: 'app-payment-initiation',
  standalone: true,

  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatIconModule,
    MatButtonModule,
  ],

  templateUrl: './payment-initiation.component.html',
  styleUrls: ['./payment-initiation.component.scss'],
})
export class PaymentInitiationComponent implements OnInit {
  // =========================================================
  // SIDEBAR
  // =========================================================

  sidebarCollapsed = false;

  // =========================================================
  // PAYMENT FLOW
  // =========================================================

  currentStep: FlowStep = 'FORM';

  // =========================================================
  // BACKEND DATA
  // =========================================================

  accounts: UserAccount[] = [];

  allBeneficiaries: Beneficiary[] = [];

  verifiedBeneficiaries: Beneficiary[] = [];

  nonVerifiedBeneficiaries: Beneficiary[] = [];

  // =========================================================
  // SELECTED BENEFICIARY
  // =========================================================

  selectedBeneficiary: Beneficiary | null = null;
  // PAYMENT FLOW
  // =========================================================
  // PAYMENT FORM
  // =========================================================

  paymentForm!: FormGroup;

  // =========================================================
  // PROCESSING
  // =========================================================

  isSubmitting = false;

  processingStage = '';

  // =========================================================
  // BACKEND RESPONSE
  // =========================================================

  completedPayment: Payment | null = null;

  fraudCheckResult: FraudCheck | null = null;

  // =========================================================
  // PAYMENT TYPES
  // =========================================================

  paymentTypes: ('Transfer' | 'Bill Payment' | 'Other')[] = [
    'Transfer',
    'Bill Payment',
    'Other',
  ];

  // =========================================================
  // PAYMENT MODES
  // =========================================================

  paymentModes: ('IMPS' | 'NEFT' | 'RTGS' | 'UPI')[] = [
    'IMPS',
    'NEFT',
    'RTGS',
    'UPI',
  ];

  // =========================================================
  // CUSTOMER ID
  // =========================================================

  /*
   * For now customer ID = 1.
   *
   * Later replace this with the logged-in customer ID.
   */
  customerId = 1;

  // =========================================================
  // CONSTRUCTOR
  // =========================================================

  constructor(
    private fb: FormBuilder,
    private paymentService: PaymentInitiationService,
    private router: Router,
  ) {}

  // =========================================================
  // INIT
  // =========================================================

  ngOnInit(): void {
    this.initForm();

    // Load beneficiaries
    this.paymentService.loadBeneficiaries();

    // Load accounts and beneficiaries
    this.loadInitialData();
  }

  // =========================================================
  // CREATE FORM
  // =========================================================

  private initForm(): void {
    this.paymentForm = this.fb.group({
      /*
       * Payment ID is generated by backend.
       */
      payment_id: [null],

      /*
       * Sender account
       */
      from_account_no: ['', [Validators.required]],

      /*
       * Selected beneficiary
       */
      beneficiary_id: ['', [Validators.required]],

      /*
       * Receiver account
       *
       * Automatically filled when
       * beneficiary is selected.
       */
      to_account_no: ['', [Validators.required]],

      /*
       * Payment amount
       */
      amount: [null, [Validators.required, Validators.min(0.01)]],

      /*
       * Payment type
       */
      payment_type: ['Transfer', [Validators.required]],

      /*
       * Payment mode
       */
      payment_mode: ['IMPS', [Validators.required]],

      /*
       * Optional description
       */
      description: [''],
    });

    // Listen for beneficiary selection
    this.paymentForm
      .get('beneficiary_id')
      ?.valueChanges.subscribe((beneficiaryId) => {
        this.onBeneficiarySelect(Number(beneficiaryId));
      });
  }

  // =========================================================
  // LOAD ACCOUNTS AND BENEFICIARIES
  // =========================================================

  private loadInitialData(): void {
    // =======================================================
    // LOAD ACCOUNTS
    // =======================================================

    this.paymentService.getAccounts(this.customerId).subscribe({
      next: (accounts) => {
        console.log('Accounts loaded from DB:', accounts);

        this.accounts = accounts;

        /*
         * Automatically select first account
         * if available.
         */
        if (this.accounts.length > 0) {
          this.paymentForm.patchValue({
            from_account_no: this.accounts[0].account_no,
          });
        }
      },

      error: (error) => {
        console.error('Error loading accounts:', error);

        alert('Unable to load accounts.');
      },
    });

    // =======================================================
    // LOAD BENEFICIARIES
    // =======================================================

    this.paymentService.getBeneficiaries().subscribe({
      next: (beneficiaries) => {
        console.log('Beneficiaries loaded from DB:', beneficiaries);

        this.allBeneficiaries = beneficiaries;

        /*
         * Verified beneficiaries
         */
        this.verifiedBeneficiaries = beneficiaries.filter(
          (b) => b.status === 'Verified',
        );

        /*
         * Non-verified beneficiaries
         */
        this.nonVerifiedBeneficiaries = beneficiaries.filter(
          (b) => b.status !== 'Verified',
        );
      },

      error: (error) => {
        console.error('Error loading beneficiaries:', error);

        alert('Unable to load beneficiaries.');
      },
    });
  }

  // =========================================================
  // TOGGLE SIDEBAR
  // =========================================================

  toggleSidebar(): void {
    this.sidebarCollapsed = !this.sidebarCollapsed;
  }

  // =========================================================
  // SELECT BENEFICIARY
  // =========================================================

  onBeneficiarySelect(beneficiaryId: number): void {
    // -------------------------------------------------------
    // Nothing selected
    // -------------------------------------------------------

    if (!beneficiaryId) {
      this.selectedBeneficiary = null;

      this.paymentForm.patchValue({
        to_account_no: '',
      });

      return;
    }

    // -------------------------------------------------------
    // Find beneficiary
    // -------------------------------------------------------

    const found = this.allBeneficiaries.find(
      (b) => b.beneficiary_id === beneficiaryId,
    );

    // -------------------------------------------------------
    // Beneficiary not found
    // -------------------------------------------------------

    if (!found) {
      this.selectedBeneficiary = null;

      this.paymentForm.patchValue({
        to_account_no: '',
      });

      return;
    }

    // -------------------------------------------------------
    // Only verified beneficiaries
    // -------------------------------------------------------

    if (found.status !== 'Verified') {
      this.selectedBeneficiary = null;

      this.paymentForm.patchValue({
        beneficiary_id: '',
        to_account_no: '',
      });

      alert('Only verified beneficiaries can be selected.');

      return;
    }

    // -------------------------------------------------------
    // Store beneficiary
    // -------------------------------------------------------

    this.selectedBeneficiary = found;

    // -------------------------------------------------------
    // Automatically fill receiver account
    // -------------------------------------------------------

    this.paymentForm.patchValue({
      to_account_no: found.account_no,
    });

    console.log('Selected beneficiary:', found);
  }

  // =========================================================
  // GO TO REVIEW
  // =========================================================

  /*
   * IMPORTANT:
   *
   * This method DOES NOT call the backend.
   *
   * It only moves the user to the review screen.
   *
   * Payment is created only after
   * the user clicks Confirm.
   */
  goToReview(): void {
    // Validate form
    if (this.paymentForm.invalid) {
      this.paymentForm.markAllAsTouched();

      return;
    }

    // Validate beneficiary
    if (!this.selectedBeneficiary) {
      alert('Please select a verified beneficiary.');

      return;
    }

    // Go to review
    this.currentStep = 'REVIEW';
  }

  // =========================================================
  // EDIT PAYMENT
  // =========================================================

  editPayment(): void {
    this.currentStep = 'FORM';
  }

  // =========================================================
  // CONFIRM PAYMENT
  // =========================================================

  /*
   * This is where the actual backend flow starts.
   *
   * STEP 1:
   * Create Payment
   *
   * STEP 2:
   * Backend returns payment_id
   *
   * STEP 3:
   * Process payment using payment_id
   *
   * STEP 4:
   * Existing Milestone 1 TransactionService
   * performs the actual money transfer.
   */
  confirmPayment(): void {
    // -------------------------------------------------------
    // Validate form
    // -------------------------------------------------------

    if (this.paymentForm.invalid) {
      this.paymentForm.markAllAsTouched();

      return;
    }

    // -------------------------------------------------------
    // Validate beneficiary
    // -------------------------------------------------------

    if (!this.selectedBeneficiary) {
      alert('Please select a verified beneficiary.');

      return;
    }

    // -------------------------------------------------------
    // Start processing
    // -------------------------------------------------------

    this.currentStep = 'PROCESSING';

    this.isSubmitting = true;

    this.processingStage = 'Creating payment request...';

    // -------------------------------------------------------
    // Get form values
    // -------------------------------------------------------

    const formValues = this.paymentForm.value;

    // -------------------------------------------------------
    // Create payment payload
    //
    // Do NOT send:
    //
    // payment_id
    // transaction_ref
    // payment_status
    // initiated_at
    // updated_at
    //
    // Backend generates these.
    // -------------------------------------------------------

    const payload: Payment = {
      from_account_no: formValues.from_account_no,

      to_account_no: formValues.to_account_no,

      beneficiary_id: Number(formValues.beneficiary_id),

      amount: Number(formValues.amount),

      payment_type: formValues.payment_type,

      payment_mode: formValues.payment_mode,

      description: formValues.description
        ? formValues.description.trim()
        : undefined,
    };

    console.log('Payment initiation request:', payload);

    // =======================================================
    // STEP 1
    // CREATE PAYMENT
    // =======================================================

    this.paymentService.initiatePayment(payload).subscribe({
      next: (payment: Payment) => {
        console.log('Payment created:', payment);

        /*
         * Make sure backend generated
         * payment ID.
         */
        if (!payment.payment_id) {
          console.error('Backend did not return payment_id', payment);

          this.isSubmitting = false;

          this.currentStep = 'FORM';

          alert('Payment was created but payment ID was not returned.');

          return;
        }

        // -------------------------------------------------
        // STEP 2
        // Process payment
        // -------------------------------------------------

        this.processingStage = 'Processing payment...';

        console.log('Processing payment ID:', payment.payment_id);

        this.paymentService.processPayment(payment.payment_id).subscribe({
          next: (response: Payment) => {
            console.log('Payment processed successfully:', response);

            // -------------------------------------------
            // Store backend response
            // -------------------------------------------

            this.completedPayment = response;

            this.fraudCheckResult = null;

            // -------------------------------------------
            // Stop loading
            // -------------------------------------------

            this.isSubmitting = false;

            // -------------------------------------------
            // Success
            // -------------------------------------------

            this.currentStep = 'SUCCESS';

            this.processingStage = 'Payment completed successfully.';
          },

          error: (error) => {
            console.error('Payment processing failed:', error);

            this.isSubmitting = false;

            this.currentStep = 'FORM';

            this.processingStage = '';

            console.error('Backend processing error:', error?.error);

            alert(
              error?.error?.message ||
                'Payment processing failed. Please try again.',
            );
          },
        });
      },

      error: (error) => {
        console.error('Payment initiation failed:', error);

        this.isSubmitting = false;

        this.currentStep = 'FORM';

        this.processingStage = '';

        console.error('Backend initiation error:', error?.error);

        alert(
          error?.error?.message ||
            'Unable to create payment. Please check the backend.',
        );
      },
    });
  }

  // =========================================================
  // RESET PAYMENT FORM
  // =========================================================

  resetForm(): void {
    // Reset flow
    this.currentStep = 'FORM';

    // Reset backend response
    this.completedPayment = null;

    // Reset fraud result
    this.fraudCheckResult = null;

    // Reset beneficiary
    this.selectedBeneficiary = null;

    // Reset processing
    this.isSubmitting = false;

    this.processingStage = '';

    // Reset form
    this.paymentForm.reset({
      from_account_no:
        this.accounts.length > 0 ? this.accounts[0].account_no : '',

      beneficiary_id: '',

      to_account_no: '',

      amount: null,

      payment_type: 'Transfer',

      payment_mode: 'IMPS',

      description: '',
    });
  }

  // =========================================================
  // FORM CONTROLS
  // =========================================================

  get f() {
    return this.paymentForm.controls;
  }
}
