spring.application.name=BankingManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/Banking
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
# M4 Document OCR
ocr.service.url=http://localhost:8000
document.upload-dir=uploads
# M4 Liveness Detection
liveness.service.url=http://localhost:8001