spring.application.name=BankingManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/Banking
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
